from enum import StrEnum


class AdapterKind(StrEnum):
    STATIC_BOARD = "static_board"
    RENDERED_BOARD = "rendered_board"
    RSS = "rss"


class RightsStatus(StrEnum):
    FILE_UPLOAD_ALLOWED = "FILE_UPLOAD_ALLOWED"
    LINK_ONLY = "LINK_ONLY"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    BLOCKED = "BLOCKED"


class DeliveryMode(StrEnum):
    DIRECT_OFFICIAL_FILE = "DIRECT_OFFICIAL_FILE"
    OFFICIAL_PAGE_ONLY = "OFFICIAL_PAGE_ONLY"
    MIRRORED_ALLOWED = "MIRRORED_ALLOWED"
    SUMMARY_ONLY = "SUMMARY_ONLY"
    BLOCKED = "BLOCKED"


class WorkflowStatus(StrEnum):
    NEW = "NEW"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PUBLISHED = "PUBLISHED"


class ProcessingState(StrEnum):
    DISCOVERED = "DISCOVERED"
    DETAIL_FETCHED = "DETAIL_FETCHED"
    FILE_IDENTIFIED = "FILE_IDENTIFIED"
    FILE_DOWNLOADED = "FILE_DOWNLOADED"
    FILE_VALIDATED = "FILE_VALIDATED"
    FILE_INVALID = "FILE_INVALID"
    TEXT_EXTRACTED = "TEXT_EXTRACTED"
    OCR_REQUIRED = "OCR_REQUIRED"
    DEDUPLICATED = "DEDUPLICATED"
    MERGED = "MERGED"
    CLASSIFIED = "CLASSIFIED"
    SUMMARIZED = "SUMMARIZED"
    SUMMARY_FAILED = "SUMMARY_FAILED"
    RIGHTS_EVALUATED = "RIGHTS_EVALUATED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PUBLISHED = "PUBLISHED"
